### ISSUE TITLE
Show all controls to the Player at game start

### ISSUE THREAD

**Issue by another-chi** [GerryDE/bauing-gamejam-ws22_23#45]
- The player needs more information about the controls, especially how to move
- Showing all controls at once at game start could overwhelm the Player
- Current thoughts: Show all controls after being inactive for a while. Or, keep the dynamic style but show dynamically how to move too. This could happen at game start and then again after inactivity for move controls only
- UI shall shall input buttons as icons. For these icons, graphics are needed

These icons are needed:

- [ ] 'A' key icon (for moving left)
- [ ] 'D' key icon (for moving right)
- [ ] 'W' key icon (interact)
- [ ] 'Q' key icon (Pause)
- [ ] 'E' key icon (Upgrade)

**Comment by Feliza1992** [comment]
solved through unity
