### ISSUE TITLE
ui fix numbers bigger than 100

### ISSUE THREAD

**Issue by Feliza1992** [GerryDE/bauing-gamejam-ws22_23#86]
from 100 and up we get visual bugs. 
![grafik](https://github.com/user-attachments/assets/4469a4aa-cf24-46a5-93e3-fcef9c2dcb39)
to do: fix this  by giving more space and limit resources to 999

**Comment by another-chi** [comment]
Sounds good. Limits could also fix some problems related to the statue updates
