### ISSUE TITLE
control choices

### ISSUE THREAD

**Issue by Feliza1992** [GerryDE/bauing-gamejam-ws22_23#87]
i got a request to mind azerty keyboards and show users to use arrow keys not just wasd, with up and down being used for upgrades and repairs. we need to discuss this

**Comment by another-chi** [comment]
We could simply make  arrow keys work for moving and upgrading as well (should very easy thanks to the new input system from Unity :D), but then need to make this visible in the tutorial

**Comment by Feliza1992** [comment]
sounds good

**Comment by another-chi** [comment]
@Feliza1992 Idea: CTRL keys as additional keys for upgrades (since CTRL-Right is next to the arrow keys) and ESC for Pausing the game? As said this can be added easily in Unity. I'd adjust the UI to make these buttons visible as well then
