### ISSUE TITLE
enemies dont spawn past wave 4

### ISSUE THREAD

**Issue by Feliza1992** [GerryDE/bauing-gamejam-ws22_23#89]
important to fix. wave 5 never arrives

**Comment by another-chi** [comment]
The game should end after wave 3 (Tutorial is Wave 0). Then it seems the actual problem is that the end screen wasn't shown

**Comment by Feliza1992** [comment]
what about the bosses and so forth? are we ending it after just 3 waves of enemies as opposed to our 25ish waves before? this seems rather short

**Comment by another-chi** [comment]
Currently, we have 5 sub-waves per wave. 4 sub-waves are spawning 3 enemies each. The 5. sub-wave is the boss fight. We could either increase the amount of waves (we actually do have 2 unused boss fights we could re-use then xD), increase the amount of sub-waves increasingly with each wave and/or increase the amount of spawning enemies within the sub-waves

**Comment by Feliza1992** [comment]
let me correct a misunderstanding. the game didnt spawn anything anymore before the  first boss, so translate me saying waves to meaning subwaves.
