### ISSUE TITLE
mining sound spielt zu lange

### ISSUE THREAD

**Issue by Feliza1992** [GerryDE/bauing-gamejam-ws22_23#95]
der sound spielt auch noch nachdem man nicht mehr abbaut. er soll enden sobald man aufhört mit der spitzhacke drauf zu hauen

**Comment by another-chi** [comment]
Ich glaube, der Soundeffekt ist etwas zu lang weswgen das den  Eindruckm macht. Man könnte es also möglicherweise easy fixen in dem man den Soundeffekt verkürzt. Falls nicht, dann wohl doch ein anderer Bug aber ich schau mal

**Comment by another-chi** [comment]
Hatten bereits Soundeffekte im Projekt, die wir eigentlich bevorzugt verwenden wollten xD
Werden nun auch tatsächlich verwendet und hat das Problem direkt mit gelöst :D
