### ISSUE TITLE
2 bäume fällen zeitgleich möglich

### ISSUE THREAD

**Issue by Feliza1992** [GerryDE/bauing-gamejam-ws22_23#98]
es gibt wohl einen sweet spot zwischen 2 bäumen wo man stehen kann um beide zeitgleich abzuholzen. einer nach dem anderen wäre wie es sein soll würde ich sagen

**Comment by another-chi** [comment]
Eine mögliche einfache Lösung wäre sicherzustellen, dass alle interagierbaren Objekte weit genug auseinanderstehen, sodass man keine 2 gleichzeitig abbauen kann. Heißt wir sollten dann die Bäume nicht mehr in einer zufälligen Range spawnen lassen, sondern immer jeweils an den gleichen Stellen. Evtl. sonst noch die Kollisionsboxen ein wenig runterregeln, sodass der Spiele nicht mit 2 Objekten gleichzeitig überlappt. Noch offen zur Diskussion
