### ISSUE TITLE
skip tutorial checkbox unclickable

### ISSUE THREAD

**Issue by Feliza1992** [GerryDE/bauing-gamejam-ws22_23#99]

**Comment by another-chi** [comment]
It's indented to not be clickable since we have no mouse control in the game. It can be toggled by using the S key in the main menu. I guess it'd be confusing when you have mouse control for this only specific checkbox only. Or do you see any need to change this @Feliza1992?

**Comment by Feliza1992** [comment]
Hmn es ist verwirrend, da man normalerweise auf checkboxen clicken kann. vielleicht wäre ein schriftzug wie Aktiv oder Inaktiv oder so etwas sinnvoller

**Comment by another-chi** [comment]
Wollte das gerade ausprobieren und hab den Eindruck, dass man dann in eher schwer verständliche Doppel-Verneinungen geriet (sowas wie ` Skip tutorial (Disabled)`). Ich würds sonst besser so machen, dass man in dem Fall dann einfach auch die Maus verwenden kann, dasselbe für den Volume Slider
